version: 2

jobs:
  build:
    machine: true
    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Install Test Dependencies
          background: true
          command: |
            sudo touch /etc/udev/rules.d/85-makemkv.rules && sudo chmod g+w $_ && sudo chgrp $(id -g) $_
            pyenv install 3.6.1 && pyenv local $_
            pip install tox

      - run:
          name: Build Shared Object
          command: |
            cd lib
            gcc -o force_umask.so force_umask.c -fPIC -shared
            git diff --no-ext-diff --quiet --exit-code force_umask.so || cp -v force_umask.so ~/

      - store_artifacts:
          path: ~/force_umask.so

      - run:
          name: Update Docker
          command: |
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg |sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt-get update
            sudo apt-get install -y docker-ce

      - run:
          name: Install CDEmu
          background: true
          command: |
            sudo tee /etc/udev/rules.d/85-vhba.rules <<< 'KERNEL=="vhba_ctl", MODE="0660", GROUP="circleci"'
            sudo add-apt-repository -y ppa:cdemu/ppa && sudo apt-get update
            sudo apt-get install -y cdemu-client linux-headers-$(uname -r)
            eval $(dbus-launch --sh-syntax |tee ~/.cdemu |tee -a ~/.bashrc)
            cdemu status

      - run:
          name: Build Dockerfile
          command: docker build . -t robpol86/makemkv

      - run:
          name: Run Tests
          command: |
            while ps ux |grep -v grep |grep 'bash.*pip install tox'; do sleep 2; done
            while ps ux |grep -v grep |grep 'bash.*85-vhba.rules'; do sleep 2; done
            source ~/.cdemu
            cd tests && tox
